### ISSUE TITLE
Missing sudo password

### ISSUE THREAD

**Issue by novski** [maas/maas-ansible-playbook#106]
How to add sudo password?

```
TASK [Ensure dist is up to date] 
fatal: [maas]: FAILED! => {"msg": "Missing sudo password"}
```

**Comment by novski** [comment]
```
--extra-vars="maas_version=3.3 ansible_sudo_pass=somepass maas_postgres_password=somepass maas_installation_type=snap maas_url=http://192.168.0.2:5240/MAAS"
```
Also, I read here: https://www.shellhacks.com/ansible-sudo-a-password-is-required/ and here https://stackoverflow.com/questions/21870083/specify-sudo-password-for-ansible that there must be more than one solution.

Thanks

**Comment by ElineMaaikedeWeerd** [comment]
@novski thanks, glad to hear it's working now. As a final note, adding `-K` or equivalently `--ask-become-pass` avoids having the password plaintext in the command line which is preferable for the obvious reasons, so e.g. `ansible-playbook -i hosts --extra-vars"extra vars" -K ./site.yaml`
