### ISSUE TITLE
maas_open_udp_ports variable is not set correctly when deploying region+rack controller

### ISSUE THREAD

**Issue by jklare** [maas/maas-ansible-playbook#125]
For the scenarion when deploying region and rack controller on the same node, the group_vars defined in 'group_vars/maas_rack_controller/60-firewall' and 'group_vars/maas_region_controller/60-firewall' will both be read and since ansible does not merge arrays, but just uses the latest definition, the array defined in 'group_vars/maas_region_controller/60-firewall' will win (files are sorted alphanumerically) and set 'maas_open_udp_ports' to '[53, 123, 514, 5240]'. This means, that the additional ports '67:69' (which are included in the array defined in 'group_vars/maas_rack_controller/60-firewall') will not be opened.
I am currently trying to figure out a good solution for this problem and will hopefully come up with something lean and a fitting PR soon :)

**Comment by jklare** [comment]
After doing some more debugging, i realised that this is also true for all the other ports specifically set for the rack, but not the region controller (and vice versa).

**Comment by jklare** [comment]
Just as a side note here and out of curiosity: Is there any reason why iptables was chosen to implement the firewall port configuration instead of ufw (https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html) like documented here https://maas.io/docs/how-to-improve-maas-security#heading--firewalls ?

**Comment by ElineMaaikedeWeerd** [comment]
@jklare ufw is an interface to iptables. The iptables module is included in ansible-core unlike the ufw module, as such it makes more sense to use iptables
