### ISSUE TITLE
ERROR! the role 'maas_postgres' was not found in

### ISSUE THREAD

**Issue by classbasics** [maas/maas-ansible-playbook#130]
ERROR! the role 'maas_postgres' was not found in ... maas-ansible-playbook/site.yaml': line 59, column 7,

Not sure what to do with roles. Some Googling goes to ansible-galaxy

************
not sure what to include for maas_pacemaker_stonith_params:, happy to accept maas_pacemaker_fencing_driver: ipmilan

maas_pacemaker_fencing_driver: The Pacemaker STONITH fencing driver, defaults to ipmilan

maas_pacemaker_stonith_params: The parameters specific to the fencing driver selected. These must be defined when using Pacemaker, to see the parameters of a given driver, run stonith_admin --metadata --agent iplam

**Comment by SK1Y101** [comment]
can you share your hosts file and execution command, might shed some light on the first issue. Looks like you don't have a postgres host defined.

@cpg1111 you interacted a lot with the pacemaker stuff here, can you weigh in?

**Comment by classbasics** [comment]
Thanks Jack,

I employed somebody else to set up the system.
Will probably just be Kubesphere on OVH bare metal.
Thanks for your help.

Regards,
 Damien
