### ISSUE TITLE
MAAS fails at database migrations

### ISSUE THREAD

**Issue by SK1Y101** [maas/maas-ansible-playbook#41]
# Problem
Ansible Playbooks fail to migrate MAAS database.

#### Error
(Error message cut down for brevity, raw error is accessible [here](https://pastebin.canonical.com/p/t2VkCB6kP3/))
```Python
fatal: [10.10.0.17]: FAILED! => {"changed": true, "cmd": ["maas-region", "migrate"],
...
"django.db.utils.OperationalError: could not connect to server: Connection timed out", "\tIs the server running on host \"10.10.0.31\" and accepting", "\tTCP/IP connections on port 5432?"], "stdout": "", "stdout_lines": []}
```
#### Config
```INI
[maas_postgres_primary]
10.10.0.31 ansible_user=ubuntu

[maas_postgres_secondary]

# DO NOT MODIFY this group
[maas_postgres:children]
maas_postgres_primary
maas_postgres_secondary

[maas_proxy]
10.10.0.31 ansible_user=ubuntu

[maas_region_controller]
10.10.0.17 ansible_user=ubuntu

[maas_rack_controller]

```

#### Command
```BASH
ansible-playbook site.yaml  -i hosts --extra-vars "maas_version=3.2 maas_postgres_password=test maas_postgres_replication_password=test maas_installation_type=deb admin_username=admin admin_password=admin maas_url=http://10.10.0.17:5240/MAAS"
```

# Steps to replicate
1. create two lxd containers
2. assign `maas_postgres_primary` and `maas_proxy` roles to one, and `maas_region_controller` to the other.
3. run `ansible-playbooks` with required variables
4. process will hang and eventually fail at `TASK [maas_region_controller : Migrate MAAS database]`

# Additional Testing
Cursory testing suggests this problem only occurs when the MAAS proxy is in use and on the same host as another role.
| Host Configurations | MAAS install | Failure |
|--------|-------------------|----------|
| 1: postgres + proxy, 2: region | Deb | Yes |
| 1: postgres + proxy, 2: region | Snap | Yes |
| 1: postgres, 2: proxy + region | Deb | Yes |
| 1: postgres, 2: proxy, 3: region | Deb | No |
| 1: postgres, 2: region | Deb | No |

**Comment by ElineMaaikedeWeerd** [comment]
I'm wondering if your last fail cause fails on add apt repository and not on database migration?

The PR might fix this, but requires some reviewing

**Comment by SK1Y101** [comment]
I didn't see an apt failure when rerunning the test on the latest branch, could be a hit-or-miss error?

I did have an apt failure when I didn't specify the maas_version, it defaults to latest so snap installs correctly, but `ppa:maas/latest` might not be a valid url for deb installs.
