### ISSUE TITLE
remove possibly redundent task to define maas url

### ISSUE THREAD

**Issue by samuelallan72** [maas/maas-ansible-playbook#61]
This task:

https://github.com/maas/maas-ansible-playbook/blob/db80c9b7ebefd069809e6368e280ed38cd968532/roles/maas_region_controller/tasks/install_maas.yaml#L67-L70

Since the value of `maas_url` in the maas regiond.conf and rackd.conf is directly templated out with the value of `maas_url` ansible variable, this seems redundent and confusing.

Can it be removed?  Or maybe there's a hidden purpose that should be documented?

**Comment by ElineMaaikedeWeerd** [comment]
Closing this, since this task has been removed since this issue was raised. It is indeed directly taken from the ansible variable, and the playbooks will throw an error if the variable is undefined.
