### ISSUE TITLE
teardown ansible error. 

### ISSUE THREAD

**Issue by zmsp** [maas/maas-ansible-playbook#98]
The Ansible teardown script encounters an issue when attempting to remove the "maas" package using the command specified in the "teardown.yaml" file. The command assumes that "maas" was installed via the "deb" package and attempts to remove it using the "apt" command. However, if "maas" was installed via the "snap" package, the command will fail because the regex pattern used in the command matches the "snap" package name.
On teardown.yaml for both roles/maas_rack_controller/teardown.yaml and maas_region_controller/teardown.yaml
```
# - name: Uninstall MAAS - deb
#   ansible.builtin.apt:
#     name: "maas*"
#     purge: true
#     state: absent


```

**Comment by SK1Y101** [comment]
The tearown command uninstalls both snap and deb, irrespective of which method was used to install.
Have you encountered a breaking error with this method while using the playbooks? We can change it to use similar checks as in the install

**Comment by ElineMaaikedeWeerd** [comment]
I’ve encountered this as well. Marked as bug, will look into a fix asap

**Comment by SK1Y101** [comment]
In theory we could parse "apt list <PKG>" or "snap info <PKG>" to determine the install method

**Comment by zmsp** [comment]
I believe the wildcard  "maas*" breaks it.
